# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{solver}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Javier Goizueta"]
  s.date = %q{2010-06-29}
  s.description = %q{This numeric solver is an example of the use of Flt}
  s.email = %q{jgoizueta@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/solver.rb",
     "lib/solver/base.rb",
     "lib/solver/function.rb",
     "lib/solver/psolver.rb",
     "lib/solver/rfsecant.rb",
     "lib/solver/secant.rb",
     "test/helper.rb",
     "test/test_function.rb",
     "test/test_psolver.rb",
     "test/test_rfsecant.rb",
     "test/test_secant.rb"
  ]
  s.homepage = %q{http://github.com/jgoizueta/solver}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new("> 1.9.1")
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Numeric solver to exercise the Flt library}
  s.test_files = [
    "test/helper.rb",
     "test/test_function.rb",
     "test/test_psolver.rb",
     "test/test_rfsecant.rb",
     "test/test_secant.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<flt>, [">= 1.3.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<flt>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<flt>, [">= 1.3.0"])
  end
end

